In [1]:
import pandas as pd
import numpy as np

### Q1. Pandas version
- 2.3.1

In [2]:
pd.__version__

'2.3.1'

In [3]:
data = pd.read_csv("car_fuel_efficiency.csv")

### Q2. Records count
How many records are in the dataset?
- 9704

In [130]:
data.shape[0]

9704

### Q3. Fuel types
How many fuel types are presented in the dataset?
- 2

In [116]:
data['fuel_type'].nunique()

2

### Q4. Missing values
How many columns in the dataset have missing values?
- 4

In [129]:
missing = [x for x in data.isna().sum() if x != 0]

len(missing)

4

### Q5. Max fuel efficiency
What's the maximum fuel efficiency of cars from Asia?
- ~23.75

In [35]:
asia = data[data['origin'] == 'Asia']
max(asia['fuel_efficiency_mpg'])

23.759122836520497

### Q6. Median value of horsepower

1. Find the median value of `horsepower` column in the dataset.
2. Next, calculate the most frequent value of the same `horsepower` column.
3. Use `fillna` method to fill the missing values in `horsepower` column with the most frequent value from the previous step.
4. Now, calculate the median value of `horsepower` once again.

Has it changed?
- No

In [36]:
data['horsepower'].median()

np.float64(149.0)

In [38]:
horsepower_mode = data['horsepower'].mode()[0]

In [39]:
data['horsepower'].fillna(horsepower_mode)

0       159.0
1        97.0
2        78.0
3       152.0
4       140.0
        ...  
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

In [40]:
data['horsepower'].median()

np.float64(149.0)

### Q7. Sum of weights

1. Select all the cars from Asia
2. Select only columns `vehicle_weight` and `model_year`
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it `X`.
5. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
6. Invert `XTX`.
7. Create an array `y` with values `[1100, 1300, 800, 900, 1000, 1100, 1200]`.
8. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.

#### What's the sum of all the elements of the result?
~0.51

In [131]:
cols = ['vehicle_weight', 'model_year']
new_asia = asia[cols].copy()

X = (new_asia.head(7)).to_numpy()

X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [109]:
XTX = X.T @ X
XTX

array([[62248334.33150761, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [110]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [111]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

w = (XTX_inv @ X.T) @ y

w.sum()

np.float64(0.5187709081074006)